/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   botData.cpp                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: ozahir <ozahir@student.1337.ma>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/07/24 22:27:45 by ozahir            #+#    #+#             */
/*   Updated: 2023/07/26 20:35:04 by ozahir           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "Server.hpp"

void setBotData(std::vector<std::string> &activities)
{
    activities.push_back("Back up important computer files");
    activities.push_back("Bake a pie with some friends");
    activities.push_back("Bake pastries for you and your neighbor");
    activities.push_back("Bake something you've never tried before");
    activities.push_back("Binge watch a trending series");
    activities.push_back("Buy a new house decoration");
    activities.push_back("Catch up on world news");
    activities.push_back("Catch up with a friend over a lunch date");
    activities.push_back("Clean out your car");
    activities.push_back("Clean out your closet and donate the clothes you've outgrown");
    activities.push_back("Clean out your garage");
    activities.push_back("Clean out your refrigerator");
    activities.push_back("Compliment someone");
    activities.push_back("Configure two-factor authentication on your accounts");
    activities.push_back("Conquer one of your fears");
    activities.push_back("Contribute code or a monetary donation to an open-source software project");
    activities.push_back("Cook something together with someone");
    activities.push_back("Create a compost pile");
    activities.push_back("Create a cookbook with your favorite recipes");
    activities.push_back("Create a meal plan for the coming week");
    activities.push_back("Create a personal website");
    activities.push_back("Create and follow a savings plan");
    activities.push_back("Create or update your resume");
    activities.push_back("Do a jigsaw puzzle");
    activities.push_back("Do something nice for someone you care about");
    activities.push_back("Do something you used to do as a kid");
    activities.push_back("Do yoga");
    activities.push_back("Donate blood at a local blood center");
    activities.push_back("Donate to your local food bank");
    activities.push_back("Draft your living will");
    activities.push_back("Draw and color a Mandala");
    activities.push_back("Draw something interesting");
    activities.push_back("Explore a park you have never been to before");
    activities.push_back("Explore the nightlife of your city");
    activities.push_back("Fill out a basketball bracket");
    activities.push_back("Find a DIY to do");
    activities.push_back("Find a charity and donate to it");
    activities.push_back("Fix something that's broken in your house");
    activities.push_back("Give your pet ten minutes of focused attention");
    activities.push_back("Go for a run");
    activities.push_back("Go for a walk");
    activities.push_back("Go on a fishing trip with some friends");
    activities.push_back("Go on a long drive with no music");
    activities.push_back("Go see a Broadway production");
    activities.push_back("Go see a movie in theaters with a few friends");
    activities.push_back("Go stargazing");
    activities.push_back("Go swimming with a friend");
    activities.push_back("Go to a concert with local artists with some friends");
    activities.push_back("Go to a concert with some friends");
    activities.push_back("Go to a karaoke bar with some friends");
    activities.push_back("Go to a local thrift shop");
    activities.push_back("Go to a music festival with some friends");
    activities.push_back("Go to a nail salon");
    activities.push_back("Go to an escape room");
    activities.push_back("Go to the gym");
    activities.push_back("Go to the library and find an interesting book");
    activities.push_back("Have a bonfire with your close friends");
    activities.push_back("Have a football scrimmage with some friends");
    activities.push_back("Have a jam session with your friends");
    activities.push_back("Have a paper airplane contest with some friends");
    activities.push_back("Have a photo session with some friends");
    activities.push_back("Have a picnic with some friends");
    activities.push_back("Hold a video game tournament with some friends");
    activities.push_back("Hold a yard sale");
    activities.push_back("Host a movie marathon with some friends");
    activities.push_back("Improve your touch typing");
    activities.push_back("Invite some friends over for a game night");
    activities.push_back("Khra ltanjawa flap7ar");
    activities.push_back("Learn Express.js");
    activities.push_back("Learn GraphQL");
    activities.push_back("Learn Javascript");
    activities.push_back("Learn Kotlin");
    activities.push_back("Learn Morse code");
    activities.push_back("Learn a new programming language");
    activities.push_back("Learn a new recipe");
    activities.push_back("Learn about a distributed version control system such as Git");
    activities.push_back("Learn about the Golden Ratio");
    activities.push_back("Learn and play a new card game");
    activities.push_back("Learn calligraphy");
    activities.push_back("Learn how the internet works");
    activities.push_back("Learn how to beatbox");
    activities.push_back("Learn how to fold a paper crane");
    activities.push_back("Learn how to french braid hair");
    activities.push_back("Learn how to iceskate or rollerskate");
    activities.push_back("Learn how to make a website");
    activities.push_back("Learn how to make an Alexa skill");
    activities.push_back("Learn how to play a new sport");
    activities.push_back("Learn how to use a french press");
    activities.push_back("Learn how to use an Arduino");
    activities.push_back("Learn how to whistle with your fingers");
    activities.push_back("Learn how to write in shorthand");
    activities.push_back("Learn origami");
    activities.push_back("Learn the Chinese erhu");
    activities.push_back("Learn the NATO phonetic alphabet");
    activities.push_back("Learn the periodic table");
    activities.push_back("Learn to greet someone in a new language");
    activities.push_back("Learn to play a new instrument");
    activities.push_back("Learn to sew on a button");
    activities.push_back("Learn to write with your nondominant hand");
    activities.push_back("Learn woodworking");
    activities.push_back("Listen to a new music genre");
    activities.push_back("Listen to a new podcast");
    activities.push_back("Listen to music you haven't heard in a while");
    activities.push_back("Listen to your favorite album");
    activities.push_back("Look at pictures and videos of cute animals");
    activities.push_back("Look at your finances and find one way to save money");
    activities.push_back("Make a bucket list");
    activities.push_back("Make a budget");
    activities.push_back("Make a couch fort");
    activities.push_back("Make a new friend");
    activities.push_back("Make a scrapbook with pictures of your favorite memories");
    activities.push_back("Make a simple musical instrument");
    activities.push_back("Make a to-do list for your week");
    activities.push_back("Make bread from scratch");
    activities.push_back("Make homemade ice cream");
    activities.push_back("Make tie dye shirts");
    activities.push_back("Make your own LEGO creation");
    activities.push_back("Match your storage containers with their lids");
    activities.push_back("Memorize a favorite quote or poem");
    activities.push_back("Memorize the fifty states and their capitals");
    activities.push_back("Mow your lawn");
    activities.push_back("Mow your neighbor's lawn");
    activities.push_back("Organize a bookshelf");
    activities.push_back("Organize a cluttered drawer");
    activities.push_back("Organize your basement");
    activities.push_back("Organize your dresser");
    activities.push_back("Organize your movie collection");
    activities.push_back("Organize your music collection");
    activities.push_back("Organize your pantry");
    activities.push_back("Paint the first thing you see");
    activities.push_back("Patronize a local independent restaurant");
    activities.push_back("Pick up litter around your favorite park");
    activities.push_back("Plan a trip to another country");
    activities.push_back("Plan a vacation you've always wanted to take");
    activities.push_back("Plant a tree");
    activities.push_back("Play a game of Monopoly");
    activities.push_back("Play a game of tennis with a friend");
    activities.push_back("Play a video game");
    activities.push_back("Play a volleyball match with some friends");
    activities.push_back("Play basketball with a group of friends");
    activities.push_back("Pot some plants and put them around your house");
    activities.push_back("Practice coding in your favorite language");
    activities.push_back("Prepare a 72-hour kit");
    activities.push_back("Prepare a dish from a foreign culture");
    activities.push_back("Pull a harmless prank on one of your friends");
    activities.push_back("Read a formal research paper on an interesting subject");
    activities.push_back("Rearrange and organize your room");
    activities.push_back("Repaint a room in your house");
    activities.push_back("Research a topic you're interested in");
    activities.push_back("Resolve a problem you've been putting off");
    activities.push_back("Shop at support your local farmers market");
    activities.push_back("Shred old documents you don't need anymore");
    activities.push_back("Sit in the dark and listen to your favorite music with no distractions");
    activities.push_back("Solve a Rubik's cube");
    activities.push_back("Start a band");
    activities.push_back("Start a blog for something you're passionate about");
    activities.push_back("Start a book you've never gotten around to reading");
    activities.push_back("Start a collection");
    activities.push_back("Start a daily journal");
    activities.push_back("Start a family tree");
    activities.push_back("Start a webinar on a topic of your choice");
    activities.push_back("Study a foreign language");
    activities.push_back("Surprise your significant other with something considerate");
    activities.push_back("Take a bubble bath");
    activities.push_back("Take a caffeine nap");
    activities.push_back("Take a class at your local community center that interests you");
    activities.push_back("Take a hike at a local park");
    activities.push_back("Take a nap");
    activities.push_back("Take a spontaneous road trip with some friends");
    activities.push_back("Take your cat on a walk");
    activities.push_back("Take your dog on a walk");
    activities.push_back("Teach your dog a new trick");
    activities.push_back("Text a friend you haven't talked to in a long time");
    activities.push_back("Think of a new business idea");
    activities.push_back("Try a food you don't like");
    activities.push_back("Uninstall unused apps from your devices");
    activities.push_back("Visit a nearby museum");
    activities.push_back("Visit your past teachers");
    activities.push_back("Volunteer and help out at a senior center");
    activities.push_back("Volunteer at a local animal shelter");
    activities.push_back("Volunteer at your local food bank");
    activities.push_back("Volunteer at your local food pantry");
    activities.push_back("Wash your car");
    activities.push_back("Watch a Khan Academy lecture on a subject of your choosing");
    activities.push_back("Watch a classic movie");
    activities.push_back("Watch a movie you'd never usually watch");
    activities.push_back("Watch the sunset or the sunrise");
    activities.push_back("Write a handwritten letter to somebody");
    activities.push_back("Write a list of things you are grateful for");
    activities.push_back("Write a note of appreciation to someone");
    activities.push_back("Write a poem");
    activities.push_back("Write a short story");
    activities.push_back("Write a song");
    activities.push_back("Write a thank you letter to an influential person in your life");
}